title: 'Aprendizaje y Enseñanza de la Tecnología'
subtitle: '1er Cuatrimestre'
theme: jekyll-theme-midnight
light: true
description: 'Desarrollo Colaborativo de Proyectos de Aprendizaje y Enseñanza de Tecnologías en la Nube'
acronym: AET
exclude: [ '_drafts/2021/', '_drafts/2020' ]
baseurl: '/asignatura-website-template/' # '/introduccion'
#url: https://ull-mfp-aet-2223.github.io/ull-mfp-aet-2223.github.io
guia_docente: https://www.ull.es/apps/guias/guias/view_guide_course/2223/125771143
show_downloads: false
calendario_academico: https://www.ull.es/estudios-docencia/calendario-academico/
horarios_examenes: https://www.ull.es/grados/ingenieria-informatica/informacion-academica/horarios-y-calendario-examenes/
calendario_examenes: https://docs.google.com/document/d/1j5rJyULD1c42UV4o-g85puuPlbO-DNFmaobn_vnKgKw/edit#
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
google_plus: https://plus.google.com/u/1/communities/101901734024125937720
organization: 
  url: https://github.com/ULL-MFP-AET-2223
  name: ULL-MFP-AET-2223
  master: https://github.dev/ULL-MFP-AET/ull-mfp-aet.github.io/blob/main/
apuntes_repo: https://github.com/ULL-MFP-AET/ull-mfp-aet.github.io/
campus_virtual: "https://campusdoctoradoyposgrado2223.ull.es/course/view.php?id=2223110052"
calificador: https://campusdoctoradoyposgrado2223.ull.es/grade/report/index.php?id=2223110052
tareas_en_el_campus: https://campusvirtual.ull.es/ingenieriaytecnologia/1920/mod/assign/index.php?id=201911070
profesor: "https://www.ull.es/apps/guias/guias/view_teacher_niu/984/crguezl/"
profesor_github: crguezl
chat: https://chat.google.com
future: true
bull_permanente: https://puntoq.ull.es/permalink/f
covid_ull: https://campusvirtual.ull.es/doctoradoyposgrado/course/view.php?id=201913946
dsi:
  apuntes: https://ull-esit-dsi-1819.github.io/dsi-1819/
sytws:
  url: https://ull-mii-sytws-1920.github.io/
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: "https://classroom.github.com/classrooms/108617085-ull-mfp-aet-2223"
  name: ULL-MFP-AET-2223
collections:
  tareas:
    output: true
temas:
# - title: 'Introducción al Desarrollo Colaborativo de Proyectos en la Nube'
#    url: '/tema0-introduccion/'
#    hover: 'introduccion'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con GitHub Education'
#  url: '/tema1-github-education'
#  hover: 'github-education'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con Google'
#  url: /tema2-google-app-scripts
#  hover: 'google-app-scripts' 
plugins:
  - jemoji

